In [379]:
# Sample Organization and Calculations

In [380]:
import numpy as np
import pandas as pd
import os

In [381]:
os.chdir('/project/pi_sarah_gignouxwolfsohn_uml_edu/brooke/metadata')

In [382]:
sample_data=pd.read_csv('CBC_samples.csv')

In [383]:
sample_data

,Month_year,Country,Location,CollectionDate,Transect,TransectNum,OldTagNum,NewTagNum,Species,Time_sampled,Time_processed,Sample_type,SampleNum,Health status,Sampling_notes,Tubelabel_species,Sample_physical_location,Extraction_physical_location,Date_sequenced,Notes
0,122022.0,BEL,CBC,12/5/22,CURLEW,4.0,NaN,77,OFAV,NaN,NaN,Core_EtOH,2,Healthy,NaN,122022_BEL_CBC_T4_2_OFAV,UML_NARWHAL_R1_B5,UML_NARWHAL_R2_B3,NaN,NaN
1,92023.0,BEL,CBC,9/25/23,CBC30N,1.0,NaN,2,PAST,NaN,NaN,Core_RNAlater,171,Healthy,CLP 90%,092023_BEL_CBC_T1_171_PAST,UML_NARWHAL_R1_B10,NaN,NaN,NaN
2,92023.0,BEL,CBC,9/25/23,CBC30N,1.0,NaN,21,PAST,NaN,NaN,Core_RNAlater,172,Healthy,No CL,092023_BEL_CBC_T1_172_PAST,UML_NARWHAL_R1_B10,NaN,NaN,NaN
3,92023.0,BEL,CBC,9/25/23,CBC30N,1.0,NaN,3,SSID,NaN,NaN,Core_RNAlater,173,Healthy,CLP 80%; DC 20%,092023_BEL_CBC_T1_173_SSID,UML_NARWHAL_R1_B10,NaN,NaN,NaN
4,92023.0,BEL,CBC,9/25/23,CBC30N,1.0,NaN,24,MCAV,NaN,NaN,Core_RNAlater,174,Healthy,CLP 10%,092023_BEL_CBC_T1_174_MCAV,UML_NARWHAL_R1_B10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990,42024.0,Belize,CBC,4/29/24,Hangman,6.0,NaN,34,OFAV,12:01,13:06,Core_RNAlater,1138,Healthy,NaN,NaN,NaN,NaN,NaN,NaN
1991,42024.0,Belize,CBC,4/29/24,Hangman,6.0,NaN,35,OFAV,12:06,13:07,Core_frozen,1208,Healthy,NaN,NaN,NaN,NaN,NaN,NaN
1992,42024.0,Belize,CBC,4/29/24,Hangman,6.0,NaN,35,OFAV,12:06,13:07,Core_RNAlater,1139,Healthy,NaN,NaN,NaN,NaN,NaN,NaN
1993,42024.0,Belize,CBC,4/29/24,Hangman,6.0,NaN,36,OANN,12:09,13:07,Core_frozen,1209,Healthy,NaN,NaN,NaN,NaN,NaN,NaN
1994,42024.0,Belize,CBC,4/29/24,Hangman,6.0,NaN,36,OANN,12:09,13:07,Core_RNAlater,1140,Healthy,NaN,NaN,NaN,NaN,NaN,NaN

In [384]:
# making df a little smaller
cols_drop=["Location","Sample_physical_location","Extraction_physical_location"]
sample_data.drop(columns=cols_drop,inplace=True)

In [385]:
# clean up column names
sample_data.columns

Index(['Month_year', 'Country', 'CollectionDate', 'Transect ', 'TransectNum',
       'OldTagNum', 'NewTagNum', 'Species', 'Time_sampled', 'Time_processed',
       'Sample_type', 'SampleNum', 'Health status', 'Sampling_notes',
       'Tubelabel_species', 'Date_sequenced', 'Notes'],
      dtype='object')

In [386]:
# remove space from 'Transect '
sample_data.rename(columns={'Transect ': 'Transect'}, inplace=True)
# replace space in 'Health status' with _
sample_data.rename(columns={'Health status': 'Health_status'}, inplace=True)
sample_data.columns

Index(['Month_year', 'Country', 'CollectionDate', 'Transect', 'TransectNum',
       'OldTagNum', 'NewTagNum', 'Species', 'Time_sampled', 'Time_processed',
       'Sample_type', 'SampleNum', 'Health_status', 'Sampling_notes',
       'Tubelabel_species', 'Date_sequenced', 'Notes'],
      dtype='object')

In [387]:
# convert to str
sample_data['Month_year'] = sample_data['Month_year'].astype(str)
# remove the decimal point
sample_data['Month_year'] = sample_data['Month_year'].str.replace('.0', '')

# add leading zeros where necessary
sample_data['Month_year'] = sample_data['Month_year'].str.pad(width=6, side='left', fillchar='0')
sample_data['Month_year']

0       122022
1       092023
2       092023
3       092023
4       092023
         ...
1990    042024
1991    042024
1992    042024
1993    042024
1994    042024
Name: Month_year, Length: 1995, dtype: object

In [388]:
nan_values = sample_data[sample_data['Month_year'].str.contains("nan", na=False)]
print(nan_values.head(2))
nan_values.shape
# don't know how there's no more info on these samples...may need to go through commit history and figure out what these are

     Month_year Country CollectionDate Transect  TransectNum OldTagNum  \
1152     000nan     NaN            NaN      NaN          NaN       NaN
1153     000nan     NaN            NaN      NaN          NaN       NaN

     NewTagNum Species Time_sampled Time_processed Sample_type SampleNum  \
1152       NaN     NaN          NaN            NaN         NaN       NaN
1153       NaN     NaN          NaN            NaN         NaN       NaN

     Health_status Sampling_notes Tubelabel_species Date_sequenced  \
1152           NaN            NaN            ___T__            NaN
1153           NaN            NaN            ___T__            NaN

                              Notes
1152  At UML, don't know what it is
1153  At UML, don't know what it is

(9, 17)

In [389]:
# delete na rows from only that col
sample_data = sample_data[~sample_data['Month_year'].str.contains("nan", na=False)]
# Reset index if needed
sample_data.reset_index(drop=True, inplace=True)
sample_data

,Month_year,Country,CollectionDate,Transect,TransectNum,OldTagNum,NewTagNum,Species,Time_sampled,Time_processed,Sample_type,SampleNum,Health_status,Sampling_notes,Tubelabel_species,Date_sequenced,Notes
0,122022,BEL,12/5/22,CURLEW,4.0,NaN,77,OFAV,NaN,NaN,Core_EtOH,2,Healthy,NaN,122022_BEL_CBC_T4_2_OFAV,NaN,NaN
1,092023,BEL,9/25/23,CBC30N,1.0,NaN,2,PAST,NaN,NaN,Core_RNAlater,171,Healthy,CLP 90%,092023_BEL_CBC_T1_171_PAST,NaN,NaN
2,092023,BEL,9/25/23,CBC30N,1.0,NaN,21,PAST,NaN,NaN,Core_RNAlater,172,Healthy,No CL,092023_BEL_CBC_T1_172_PAST,NaN,NaN
3,092023,BEL,9/25/23,CBC30N,1.0,NaN,3,SSID,NaN,NaN,Core_RNAlater,173,Healthy,CLP 80%; DC 20%,092023_BEL_CBC_T1_173_SSID,NaN,NaN
4,092023,BEL,9/25/23,CBC30N,1.0,NaN,24,MCAV,NaN,NaN,Core_RNAlater,174,Healthy,CLP 10%,092023_BEL_CBC_T1_174_MCAV,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,042024,Belize,4/29/24,Hangman,6.0,NaN,34,OFAV,12:01,13:06,Core_RNAlater,1138,Healthy,NaN,NaN,NaN,NaN
1982,042024,Belize,4/29/24,Hangman,6.0,NaN,35,OFAV,12:06,13:07,Core_frozen,1208,Healthy,NaN,NaN,NaN,NaN
1983,042024,Belize,4/29/24,Hangman,6.0,NaN,35,OFAV,12:06,13:07,Core_RNAlater,1139,Healthy,NaN,NaN,NaN,NaN
1984,042024,Belize,4/29/24,Hangman,6.0,NaN,36,OANN,12:09,13:07,Core_frozen,1209,Healthy,NaN,NaN,NaN,NaN
1985,042024,Belize,4/29/24,Hangman,6.0,NaN,36,OANN,12:09,13:07,Core_RNAlater,1140,Healthy,NaN,NaN,NaN,NaN

In [390]:
# confirming it dropped the right amount of rows to match nan_values
1995-9

1986

In [391]:
# Extract month and year
sample_data.loc[:,'Month'] = sample_data.loc[:,'Month_year'].str[0:2]
sample_data.loc[:,'Year'] = sample_data.loc[:,'Month_year'].str[2:]

sample_data

/tmp/ipykernel_3112/3282395172.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_data.loc[:,'Month'] = sample_data.loc[:,'Month_year'].str[0:2]
/tmp/ipykernel_3112/3282395172.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_data.loc[:,'Year'] = sample_data.loc[:,'Month_year'].str[2:]

,Month_year,Country,CollectionDate,Transect,TransectNum,OldTagNum,NewTagNum,Species,Time_sampled,Time_processed,Sample_type,SampleNum,Health_status,Sampling_notes,Tubelabel_species,Date_sequenced,Notes,Month,Year
0,122022,BEL,12/5/22,CURLEW,4.0,NaN,77,OFAV,NaN,NaN,Core_EtOH,2,Healthy,NaN,122022_BEL_CBC_T4_2_OFAV,NaN,NaN,12,2022
1,092023,BEL,9/25/23,CBC30N,1.0,NaN,2,PAST,NaN,NaN,Core_RNAlater,171,Healthy,CLP 90%,092023_BEL_CBC_T1_171_PAST,NaN,NaN,09,2023
2,092023,BEL,9/25/23,CBC30N,1.0,NaN,21,PAST,NaN,NaN,Core_RNAlater,172,Healthy,No CL,092023_BEL_CBC_T1_172_PAST,NaN,NaN,09,2023
3,092023,BEL,9/25/23,CBC30N,1.0,NaN,3,SSID,NaN,NaN,Core_RNAlater,173,Healthy,CLP 80%; DC 20%,092023_BEL_CBC_T1_173_SSID,NaN,NaN,09,2023
4,092023,BEL,9/25/23,CBC30N,1.0,NaN,24,MCAV,NaN,NaN,Core_RNAlater,174,Healthy,CLP 10%,092023_BEL_CBC_T1_174_MCAV,NaN,NaN,09,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,042024,Belize,4/29/24,Hangman,6.0,NaN,34,OFAV,12:01,13:06,Core_RNAlater,1138,Healthy,NaN,NaN,NaN,NaN,04,2024
1982,042024,Belize,4/29/24,Hangman,6.0,NaN,35,OFAV,12:06,13:07,Core_frozen,1208,Healthy,NaN,NaN,NaN,NaN,04,2024
1983,042024,Belize,4/29/24,Hangman,6.0,NaN,35,OFAV,12:06,13:07,Core_RNAlater,1139,Healthy,NaN,NaN,NaN,NaN,04,2024
1984,042024,Belize,4/29/24,Hangman,6.0,NaN,36,OANN,12:09,13:07,Core_frozen,1209,Healthy,NaN,NaN,NaN,NaN,04,2024
1985,042024,Belize,4/29/24,Hangman,6.0,NaN,36,OANN,12:09,13:07,Core_RNAlater,1140,Healthy,NaN,NaN,NaN,NaN,04,2024

In [392]:
# convert columns to datetimes 
sample_data.loc[:,'Month_year']=pd.to_datetime(sample_data['Month_year'], format = '%m%Y').dt.date
sample_data.loc[:,'Month']=pd.to_datetime(sample_data['Month'], format = '%m').dt.month_name().str.slice(stop=3)

In [393]:
# Goal: make summary df that shows how many samples were taken each year for each species - shows sum of sample types too

In [394]:
# filter for 2019 samples
s2019 = sample_data["Year"]=='2019'
samples_2019=sample_data[s2019]

In [395]:
print(sample_data['Health_status'].unique())

['Healthy' 'Diseased_Margin' 'Diseased_Tissue' nan 'CLP 100%'
 'HealthyNot_Sampled' 'HealthyTissue' 'MISS_SAMPLE' 'MiSSING' 'MISSING'
 'Diseased_tissue' 'Diseased_margin' 'Disease']

In [397]:
healthy=samples_2019['Health_status']=="Healthy"
print("Total # of healthy samples in 2019:",healthy.sum())

Total # of healthy samples in 2019: 340

In [404]:
healthy_2019=samples_2019[healthy]
print(healthy_2019['OldTagNum'].unique())
healthy_2019['OldTagNum'].value_counts(ascending=True)

['407' '413' '418' '417' '404' '422' '419' '408' '409' '412' '415' '411'
 '423' '426' '414' '421' '406' '400' '427' '420' '403' '359' '389' '393'
 '36' '34' '392' '41' '347' '387' '62' '56' '91' '47' '396' '395' '397'
 '391' '388' '382' '384' '390' '381' '386' '385' '383' '380' '394' '367'
 '304' '369' '374' '378' '21' '12flag' '370' '327' '358' '365' '300' '301'
 '363' '307' '316' '364' '321' '345' '314' '22' '23' '24' '25' '373' '28'
 '27' '29' '353' '350' '361' '379' '305' '356' '328' '343' '317' '325'
 '320' '311' '337' '355' '333' '334' '329' '335' '357' '303' '349' '346'
 '342' '354' '339' '341' '352' '348' '344' '330' '336']

OldTagNum
341       1
409       2
415       2
412       2
423       2
         ..
369       4
374       4
407       4
21        4
12flag    4
Name: count, Length: 107, dtype: int64

In [408]:
print("Total # of healthy sampled COLONIES in 2019:",healthy_2019['OldTagNum'].value_counts().shape)

Total # of healthy sampled COLONIES in 2019: (107,)

In [ ]:
# for each species in 2019, calculate total number of active tagged colonies and total num of samples taken

In [432]:
# create dictionary with necessary columns 
d={"species":[], "tagged_colonies":[], "num_samples":[]}
# loop thru each species in healthy 2019 df
species_list=healthy_2019['Species'].unique()
for specie in species_list:
    # add specie name to 'species' col
    d["species"].append(specie)
    
    # determine num of tagged colonies
    sp=healthy_2019['Species']==specie
    sp_df=healthy_2019[sp]
    colonies=sp_df["OldTagNum"].nunique()
    
    #add num of tagged colonies to dict
    d["tagged_colonies"].append(colonies)
    
    #determine num of samples
    sp_df=healthy_2019[sp]
    samples=sp_df["SampleNum"].nunique()
    
    #add to dict
    d["num_samples"].append(samples)
#convert d to df
SampleCounts_healthy2019=pd.DataFrame.from_dict(d)
SampleCounts_healthy2019

  species  tagged_colonies  num_samples
0    PSTR               21           39
1    MCAV               24           56
2    PAST               20           52
3    SSID               28           60
4    MMEA               13           34
5    CNAT                1            3

In [ ]:
# matches Sarah's sheet: https://docs.google.com/spreadsheets/d/16jlkSd8hLOTxRQoi_4W6WPUSoKN-sNtz1ChALbn6HhU/edit#gid=0
# can we add in health status too? should we make one massive table for all years and such or split it up?

In [ ]:
# there are still lots of issues with the data:
# - weird health statuses 
# - na values in important places like tagnum or date collected